### ISSUE TITLE
Build fails with test failures

### ISSUE THREAD

**Issue by jclark-dot-org** [forcedotcom/WSDL2Apex#9]
Building on Mac OS X 10.10.5 (Yosemite), fresh install of Maven via `brew install maven`, java:

    > $ java -version
    java version "1.8.0_31"
    Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

Running `mvn install` produces the following: 

    Results :

    Failed tests:   testAsyncFalse(com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest): Test 8 doesn't match expected:<...rmationByAirportCode[Response_element {(..)
      testNewClassNames(com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest): testNewClassNames doesn't match expected:<... }(..)
      testNoOperation(com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest): Test noOperation failed expected:<...   public class Echo[Date_element {(..)
      testExchange(com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest): Test testExchange failed expected:<...{(..)
      testAmazonGood(com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest): Test testAmazonGood failed expected:<... {(..)
      testBigFile(com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest): Test testBigFile failed expected:<... {(..)
      testNamespaceDependencies(com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest): Test testNamespaceDependencies failed expected:<... {(..)
      testTwoNamespaces(com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest): testTwoNamespaces a doesn't match, Async class expected:<...mple.com/stockquote.[wsdl', 'exampleComStockquoteWsdl', 'http://example.com/stockquote.xsd', 'exampleComStockquoteXsd]'};(..)
      testSqlMutations(com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest): Test sqlMutations failed expected:<...lic class getMutants[CompressedResponse_element {(..)
      testMultipleNamespace(com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest): Test testMultipleNamespace failed expected:<...   public class Echo[Date_element {(..)
      testLargeFile(com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest): testLargeFile a doesn't match expected:<...m/spectrum/services/[EOLS_PSAPLookupUS', 'wwwPbComSpectrumServicesEolsPsaplo', 'http://spectrum.pb.com/', 'spectrumPbCom', 'http://www.mapinfo.com/midev/service/geometries/v1', 'wwwMapinfoComMidevServiceGeometries', 'http://www.mapinfo.com/midev/service/units/v1', 'wwwMapinfoComMidevServiceUnitsV1', 'http://www.pb.com/spectrum/services/', 'wwwPbComSpectrumServic]es'};(..)
      testSimple(com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest): testSimple doesn't match expected:<...rmationByAirportCode[Response_element {(..)

    Tests run: 47, Failures: 12, Errors: 0, Skipped: 0

    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 13.674 s
    [INFO] Finished at: 2016-04-15T08:46:37-04:00
    [INFO] Final Memory: 18M/260M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project WSDL2Apex: There are test failures.
    [ERROR] 
    [ERROR] Please refer to /Users/jclark/ext/WSDL2Apex/target/surefire-reports for the individual test results.
    [ERROR] -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Test results files attached; xml file extension changed to support uploading to github.

[com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest.txt](https://github.com/forcedotcom/WSDL2Apex/files/220999/com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest.txt)

[TEST-com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest.xml.txt](https://github.com/forcedotcom/WSDL2Apex/files/221000/TEST-com.salesforce.ide.wsdl2apex.core.WSDL2ApexTest.xml.txt)

**Comment by dturkel** [comment]
See Issue #1, as there are issues for both Windows and Mac users.

**Comment by jclark-dot-org** [comment]
Closed as duplicate of #1, which I didn't realize was also known to affect OS X

**Comment by rmjoshi** [comment]
Thanks jclark-dot-org.. below works:

 jkraybill commented 8 days ago

A workaround to simply skip the maven test step is to add "-DskipTests=true" to your call to mvn, e.g. "mvn install package -DskipTests=true"
